// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  zuiSidebar: [
    { type: 'autogenerated', dirName: '.' },
    { type: 'link', label: 'Zed Docs', href: 'https://zui.brimdata.io/docs' }
  ],
};

module.exports = sidebars;
