// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  zedSidebar: [
    { type: 'autogenerated', dirName: '.' },
    { type: 'link', label: 'Zui Desktop App Docs', href: 'https://zui.brimdata.io/zui' }
  ],
};

module.exports = sidebars;
