// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {type: 'link', label: 'Zui Desktop Application', href: 'https://zui.brimdata.io/zui'}
  ],
};

module.exports = sidebars;
